### ISSUE TITLE
Add an extensibility model for adding a converter

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#1478]

**Comment by lgolding** [comment]
@michaelcfanning We already have this. The Multitool `convert` verb has an option `--plugin-assembly-path`, "Path to plugin assembly containing converter types".

When you run
```
Sarif.Multitool.exe convert --tool MyToolFormat --plugin-assembly-path MyConverters.dll MyToolLog.xml
```

the Multitool searches MyConverters.dll for a public, concrete class derived from `Microsoft.CodeAnalysis.Sarif.Converters.ToolFileConverterBase` and named `MyToolFormatConverter`. If the class exists, the Multitool invokes its `Convert` method; otherwise it fails.

@harleenkohli FYI.
