### ISSUE TITLE
SARIF results need to be initialized with instance GUIDs

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-sdk#1772]
If not present, we need to provide these. They need to flow to split/refactored attachments filed as bugs. This in turn allows us to relocate results in the originating SARIF file so that we can rewrite this log with filed work item details.

**Comment by ScottLouvau** [comment]
Implemented in #1786. 

To be clear, we are **not** assigning Guids by default when Results are created. This would be a big breaking change, and would affect all unit tests involving SARIF (ours and others).

This change adds 'Guids' to OptionallyEmittedData, so that Sarif.Multitool rewrite mode can have "Guids" added to the "things to add" setting to assign a Guid to each Result conveniently.

ex:
Sarif.Multitool rewrite "Sample.sarif" --insert "RegionSnippets;ContextRegionSnippets;Guids" --uriBaseIds "%SRCROOT%=C:\Local\Scan\Path" -o "Sample.ReadyForStorageAndBaselining.sarif"
