### ISSUE TITLE
Should SARIF2016.FileUrisShouldBeRelative be a warning rather than a note?

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2017]
@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Or make the validator return notes by default. My open question here is whether there's a clear pattern that allows for absolute file URIs but which also makes the enlistment root clear. That's the underlying concern this rule relates to.

A version control instance that contains the checkout path + file URIs seems perfectly reasonable. This solution is incrementally less deterministic (since drive letters can change between environments) but otherwise hits goal.

**Comment by lgolding** [comment]
Returning notes by default is a separate issue #2018. My point in filing this issue was to ask whether we'd mis-categorized this rule. I think it's more serious than a `note`. I agree that if repo root information is available, consumers who want to rebase URIs could try the repo root as a path prefix. But it's an extra burden on the consumer that wouldn't be present if only the locations were relative. That, come to think of it, might be a good criterion for something being a warning: is it likely to degrade the experience for a consumer who doesn't make a special effort to work around it?

**Comment by michaelcfanning** [comment]
I'd assumed that you'd decided to mark this item as warning in part because it's visibility was obscured by our default non-verbose output setting. I believe the actual rule here is we need to identify, where relevant, path roots. As per previous comment, a relative file uri is one mechanism but a version control provenance + absolute file uri also accomplishes goal.

And so I wonder whether we shouldn't reconsider this rule (and its name): ClarifyNonDeterministicPathRoots or something. Previously, I though we just had one acceptable solution for satisfying this requirement. Now I'm not sure there is only one viable solution.

**Comment by michaelcfanning** [comment]
@eddynaka, let's talk about this. i believe we need all relative paths in artifact locations to *not* be prefixed with a slash. That is, our standard is to include a trailing slash on base URLs to to omit leading slashes on relative URLs, which best supports combining base URLs with relative URLS per [Resolving Relative URLs](https://tools.ietf.org/html/rfc1808#section-4)  in RFC1808.

Note in particular that the `embedded URL` component in this operation is not strictly regarded as relative in case of a leading slash:

>> If the embedded URL path is preceded by a slash "/", the
           path is not relative and we skip to Step 7.

From this language, we can make a precise formulation, a relative URL which contains a leading slash is, strictly, a kind of relative URL but does not constitute an arbitrary relative *path* that can be concatenated with an arbitrary base URL.

**Comment by eddynaka** [comment]
@michaelcfanning , just to check if my understanding is correct:
foreach artifactLocation we will have to check:
1. is this location a file path? If yes, we have to end with "/"
2. is this location relative? if yes, we can NOT start with "/"

Since it is very general, should we rename this rule to be general as well? Because that won't be only applied for locations inside Results only but it would be applied for all `artifactLocations`.

**Comment by eddynaka** [comment]
@michaelcfanning , thinking again we have a problem:
based on an `Uri`, we can check if it is absolute or not. If the `Uri` is absolute, we can check if it is a `file`. But, `file` means that starts with `file:///`. It does not mean that it is a file itself.

So, based on that, I don't think we can achieve points (1) and (2) from my previous comment.

I started a draft pr: https://github.com/microsoft/sarif-sdk/pull/2167, so we can check if that is the right approach.

Thank you!

**Comment by lgolding** [comment]
(Actually `IsFile` means that the URI's [`Scheme`](https://docs.microsoft.com/en-us/dotnet/api/system.uri.scheme?view=net-5.0) property is [`Uri.UriSchemeFile`](https://docs.microsoft.com/en-us/dotnet/api/system.uri.urischemefile?view=net-5.0), whose value is `"file"`. It doesn't say anything about the URI `authority` and `path` components, which is where the slashes come from.)

**Comment by eddynaka** [comment]
Today I merged our validation that will check:
1. if the location from the file is absolute -> should we relative
2. if the location from the file is relative
  - starts with slash -> should not start with a slash
  - contains backslash -> should not contain a backslash
