### ISSUE TITLE
VSIX: Info Tab: Add margins between the rule/tool/invocation sections

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#412]
Repro Steps
1. Open the attached sarif file
2. Double-click on any of the issues in the Error List.
3. Select the Info tab.

The sections look a little cramped. We should add some margins between the sections to provide a visual break.

See attached screenshot.

![margins](https://cloud.githubusercontent.com/assets/15946080/16529703/3d242556-3f79-11e6-8e7d-4011864a26ae.png)
[AttributeAnalysis.zip](https://github.com/Microsoft/sarif-sdk/files/343919/AttributeAnalysis.zip)

**Comment by rtaket** [comment]
Fixed. Kevin added the margins.

**Comment by lgolding** [comment]
@rtaket Funny, I looked at this one and _didn't_ close it because I thought it still looked a bit cramped :) 
The margin below "Default level" is fine. I might've added space between the tool friendly name and the invocation details.

But since you're happy with it I won't reopen it, and I'll add that space in my next commit.

![image](https://cloud.githubusercontent.com/assets/11762653/16886878/a143eac2-4a8b-11e6-8689-445334d4a49f.png)
