### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#81]
There are several test failures. Console output attached:

[sarif-sdk-test-errors.txt](https://github.com/Microsoft/sarif-sdk/files/100140/sarif-sdk-test-errors.txt)

Not clear how many distinct errors this represents. Will open separate issues as appropriate.

**Comment by michaelcfanning** [comment]
There's only a single test failure in this output. The other output is due to the unit tests comprehensive negative condition testing. It's not easy to extract relevant information for real failures, we should try to clean it up. If you examine the final test summary, you'll see the actual # of failures. Search on [FAIL] to get the real thing.

Microsoft.CodeAnalysis.Sarif.Driver.Sdk.AnalyzeCommandBaseTests.UnauthorizedAccessExceptionCreatingSarifLog [FAIL]

Sarif.Driver.UnitTests  Total: 17, Errors: 0, Failed: 1, Skipped: 0, Time: 1.107s

The problem here is likely that you are running with admin privileges, which is allowing you to create log files where tests expect to get blocked. We can change the test code to provide a more reliable mechanism to raise UnauthorizedAccessException

**Comment by lgolding** [comment]
@michaelcfanning fixed this in #85.

(Michael, GitHub didn't auto-resolve it because you typoed the title of the PR ("Resolves #181" instead of "Resolves #81").
